name: Bundle Size
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: preactjs/compressed-size-action@v2
        with:
          build-script: "build"
          pattern: ".next/**/*.js"
          strip-hash: "\\b[a-f0-9]{8,}\\b"