name: French Text Validator

on: 
  push:
    paths:
      - '**.tsx'
      - '**.ts'
  pull_request:
    paths:
      - '**.tsx'
      - '**.ts'

jobs:
  validate-french:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Check for unescaped French characters
        run: |
          chmod +x ./scripts/fix_unescaped.sh
          ./scripts/fix_unescaped.sh