name: Lighthouse CI
on: 
  deployment_status:
    states: [success]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ github.event.deployment_status.target_url || 'https://propagation.vercel.app/' }}
          uploadArtifacts: false # Change to false to avoid artifact upload errors
          temporaryPublicStorage: true